name: 🐛 Bug report
description: Report an issue with VPhoneInput
labels: [ 't:bug' ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: If possible, provide a boiled down editable reproduction using a service like [StackBlitz playground](https://stackblitz.com/edit/v-phone-input?file=src%2FApp.vue&terminal=dev), JSFiddle, Codepen, CodeSandbox, or a GitHub repository. A failing unit test is even better! Otherwise provide as much information as possible to reproduce the problem. If no reproduction is provided and the information is not enough to reproduce the problem, we won't be able to give it a look **and the issue will be converted into a question and moved to discussions**.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the bug
      description: |
        1. Use X blueprint ...
        2. Run Y action ...
        3. Check log
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happens.
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Additional information
      description: Add any other context about the problem here.
  - type: markdown
    attributes:
      value: |
        ## Before creating an issue make sure that:
        - This hasn't been [reported before](https://github.com/paul-thebaud/v-phone-input/issues).
        - The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug **with no external dependencies**
