name: install

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v6
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install
