name: publish

on:
  release:
    types: [ published ]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install
      - name: Build
        run: pnpm build
      - name: Build docs
        if: ${{ !github.event.release.prerelease }}
        run: pnpm docs:build --base=/v-phone-input/
      - name: Publish prerelease
        if: ${{ github.event.release.prerelease }}
        run: pnpm publish --no-git-checks --tag next
      - name: Publish release
        if: ${{ !github.event.release.prerelease }}
        run: pnpm publish --no-git-checks
      - name: Deploy docs
        if: ${{ !github.event.release.prerelease }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist/
